// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using InstagramPatterns.InstagramApi.MediasJsonTypes;

namespace InstagramPatterns.InstagramApi.MediasJsonTypes
{

    public class Pagination
    {

        [JsonProperty("next_max_tag_id")]
        public string NextMaxTagId { get; set; }

        [JsonProperty("deprecation_warning")]
        public string DeprecationWarning { get; set; }

        [JsonProperty("next_max_id")]
        public string NextMaxId { get; set; }

        [JsonProperty("next_min_id")]
        public string NextMinId { get; set; }

        [JsonProperty("min_tag_id")]
        public string MinTagId { get; set; }

        [JsonProperty("next_url")]
        public string NextUrl { get; set; }
    }

}
