// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using InstagramPatterns.InstagramApi.UserJsonTypes;

namespace InstagramPatterns.InstagramApi.UserJsonTypes
{

    public class Meta
    {

        [JsonProperty("code")]
        public int Code { get; set; }
    }

}
