// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using InstagramPatterns.InstagramApi.ShortcodeJsonTypes;

namespace InstagramPatterns.InstagramApi.ShortcodeJsonTypes
{

    public class Likes
    {

        [JsonProperty("count")]
        public int Count { get; set; }

        [JsonProperty("data")]
        public Datum2[] Data { get; set; }
    }

}
