// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using InstagramPrint.InstagramApi.MediasJsonTypes;

namespace InstagramPrint.InstagramApi.MediasJsonTypes
{

    internal class Datum2
    {

        [JsonProperty("created_time")]
        public string CreatedTime { get; set; }

        [JsonProperty("text")]
        public string Text { get; set; }

        [JsonProperty("from")]
        public From From { get; set; }

        [JsonProperty("id")]
        public string Id { get; set; }
    }

}
