// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using InstagramPrint.InstagramApi.MediasJsonTypes;

namespace InstagramPrint.InstagramApi.MediasJsonTypes
{

    internal class UsersInPhoto
    {

        [JsonProperty("position")]
        public Position Position { get; set; }

        [JsonProperty("user")]
        public User User { get; set; }
    }

}
